### ISSUE TITLE
Update manual with -up parameter

### ISSUE THREAD

**Issue by sf-nevermore** [kcakdemir/HiCPlotter#10]
I read the code of the HiCPlotter and gladly find that the recent update adds the --upSide parameter to match the current publication style; it has not been updated to the manual page.

**Comment by kcakdemir** [comment]
Yes, I'm falling behind for updating the manual. Will do it shortly and let you know when a new version is ready...

**Comment by kcakdemir** [comment]
Just updated the manual for new parameters. Thanks for reminding me!!
