### ISSUE TITLE
Rotated heatmap plotting

### ISSUE THREAD

**Issue by Phlya** [kcakdemir/HiCPlotter#11]
Hi,

Just a suggestion to use this code instead of ndimage.rotate + imshow to create rotated heatmaps: http://stackoverflow.com/a/13477815/1304161
By also setting the axes aspect to 0.5 you can get a perfect rotated heatmap with no distortions and no requirement for interpolation (and that's what ndimage.rotate has to do to rotate by 45 degree).
Hope this is helpful.

**Comment by kcakdemir** [comment]
Thanks for the suggestion! I will look into it. For some reason, image rotation is not a very well-implemented feature in python.

**Comment by Phlya** [comment]
Yeah, unfortunately simple rotation is just not possible for images at all in maptlotlib (but I think they are aware and it's considered a bug...).

**Comment by kcakdemir** [comment]
Hey! Didnt notice, we communicated before Twitter :).
Thanks again for the suggestion. I am closing the issue but surely will try to implement the suggestion.
