### ISSUE TITLE
Shifted plots?

### ISSUE THREAD

**Issue by dalessandra** [kcakdemir/HiCPlotter#14]
Hi!

Thank you for this great tool!

I am plotting 4kb matrices and I noticed that the pixels of the plot do not mach my 4kb bins.. I think the plot may be shifted by half a bin? 

I have attached a picture of the matrix and in light blue there are two example bins.

What do you think?

Thanks!
Ale

![screen shot 2017-04-04 at 2 10 28 pm 2](https://cloud.githubusercontent.com/assets/17658899/24678729/99461d2a-1940-11e7-9d50-f2f479783bba.png)

**Comment by kcakdemir** [comment]
Hi Ale,

I have not encountered with this type of shift before. Do you mind sharing this part of your matrix, so I can try to debug the problem?

Thanks,
Kadir

**Comment by dalessandra** [comment]
Hi Kadir!

Thank you so much!!

You can download here the matrices:

chr1 intrachromosomal matrix - from HiC Pro
https://www.dropbox.com/s/bt7ktjenkpbi3oo/EGM_09_chr1_chr1.matrix.gz?dl=0 <https://www.dropbox.com/s/bt7ktjenkpbi3oo/EGM_09_chr1_chr1.matrix.gz?dl=0>

The bed files needed by HiC-plotter to map the HiC-pro generated matrices
https://www.dropbox.com/s/e1mkzraq97stfct/E_GM_4000_abs2.bed.gz?dl=0 <https://www.dropbox.com/s/e1mkzraq97stfct/E_GM_4000_abs2.bed.gz?dl=0>

These are the coordinates of the two bins:
less TNNT2_int.txt
chr1	201344000	201348000
chr1	201352000	201356000

Code:
python /share/apps/HiCPlotter/HiCPlotter.py -f /home/adallagnese/Ale/IMR90_MyoD_Project/HiC/merged_files_after_mapping_deepest_sequencing/HiC_Pro_v2.7.7/hic_results/merge_files_after_mapping/merge_maps/hic_results/matrix/M_GM/iced/4000/M_GM_4000_iced.matrix /home/adallagnese/Ale/IMR90_MyoD_Project/HiC/merged_files_after_mapping_deepest_sequencing/HiC_Pro_v2.7.7/hic_results/merge_files_after_mapping/merge_maps/hic_results/matrix/E_GM/iced/4000/E_GM_4000_iced.matrix -r 4000 -tri 1 -bed /home/adallagnese/Ale/IMR90_MyoD_Project/HiC/merged_files_after_mapping_deepest_sequencing/HiC_Pro_v2.7.7/hic_results/merge_files_after_mapping/merge_maps/hic_results/matrix/E_GM/raw/4000/E_GM_4000_abs.bed -chr chr1 -n MGM EGM -da 0 -o TNNT2_white_withDiffInt2 -mm 6 -spi 1 -s 50300 -e 50350 -si 1 -c1 -t TNNT2_int.txt TNNT2_int.txt -tl TNNT2_int TNNT2_int.txt

I was comparing two matrices..

Is there anything else you would need?

Thanks!

Best,
Ale

**Comment by kcakdemir** [comment]
Thanks a lot! This should be enough.
Please give me sometime and I will try to figure out the problem whenever I can....

**Comment by dalessandra** [comment]
Sure, thanks! Maybe I did something wrong!

Best,
Ale

**Comment by kcakdemir** [comment]
Please re-open this issue if you still experience the problem. I am closing it for the moment.
