### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by dalessandra** [kcakdemir/HiCPlotter#15]
Hi!! 

How are you?

I was wondering if you can help me with the following error message:
TypeError: 'float' object cannot be interpreted as an index

I only get it when I use -a option to plot archs. I did not use to get it before, my .bed file may not be correct. Any suggestions?

Thanks!
Ale

**Comment by kcakdemir** [comment]
Hi Ale,

Do you mind posting the error message as a whole? 
I suspect that your bed file's start/end values might be the problem.
Sorry about your other issue, it's in my mind and I will take a look at it (hopefully) very soon.

Kadir

**Comment by dalessandra** [comment]
Hi Kadir,

Thanks for your response!

Traceback (most recent call last):
  File "/share/apps/HiCPlotter/HiCPlotter.py", line 2045, in <module>
    HiCplotter(**args)
  File "/share/apps/HiCPlotter/HiCPlotter.py", line 1203, in HiCplotter
    pts = get_ellipse_coords(a=rad, b=1.0, x=center, k=1./8)
  File "/share/apps/HiCPlotter/HiCPlotter.py", line 413, in get_ellipse_coords
    pts = np.zeros((360*k+1, 2))
TypeError: 'float' object cannot be interpreted as an index

Here is part of the file of interactions:
chr22	16856001	16860001
chr22	16884001	16896001
chr22	16884001	16972001
chr22	16896001	16912001
chr22	16900001	16904001
chr22	16904001	16920001
chr22	16904001	16924001
chr22	16908001	16920001
chr22	16920001	16928001
chr22	16952001	16980001

Ale

**Comment by kcakdemir** [comment]
Hi Ale,

I will commit a new version today and that error should be resolved with the update.
Please try to run the new version and let me know if you still encounter the problem.

Kadir

**Comment by dalessandra** [comment]
Hi Kadir,

Excellent, thank you!!!

Ale

**Comment by dalessandra** [comment]
It worked great, thank you!!!
