### ISSUE TITLE
The input format of 

### ISSUE THREAD

**Issue by yuzhang0327** [kcakdemir/HiCPlotter#16]
Dear professor,

I have generated the iced matrix file using HiC-pro with Triplet sparse format (100kb), while I tried to convert it into the format like hES-nij.chr21.2 and run the command below:
python HiCPlotter.py -f matrix -n mES -chr chr2 -r 100000 -o default2 -ptd 1 -pptd 1 -s 600 -e 900 -fh 0 -w 8 -tr 10 -pi 1

but it shows error as below:
Traceback (most recent call last):
  File "HiCPlotter.py", line 1398, in <module>
    HiCplotter(**args)
  File "HiCPlotter.py", line 550, in HiCplotter
    cmatrix = log2(pow(2, ceil(log2(max(matrix))/log2(2))))
  File "/data4/software/python/2.7.12/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2297, in amax
    out=out, **kwargs)
  File "/data4/software/python/2.7.12/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

I am not sure how can I generate the right format of hES-nij.chr21.2 from Triplet sparse format ?

Best,
Yu

**Comment by kcakdemir** [comment]
Hi Yu,

You can use HiCPlotter with the output of HiC-Pro, there is no need for conversion.
Just add -tri 1 and -bed parameter, like below: 

python HiCPlotter.py -f MATRIXFILE -tri 1 -bed BEDFILE -n mES -chr chr2 -r 100000 -o default2 -ptd 1 -pptd 1 -s 600 -e 900 -fh 0 -w 8 -tr 10 -pi 1

**Comment by yuzhang0327** [comment]
Dear professor,

Thanks very much for the advice, I have tired the command, however, a new error came out as below, does that mean the format is not correct yet?

Traceback (most recent call last):
  File "HiCPlotter.py", line 1398, in <module>
    HiCplotter(**args)
  File "HiCPlotter.py", line 532, in HiCplotter
    matrix,nums,tricks,clength=read_sparseHiCdata(files[exp],chromosome,bedFile,start,end,wholeGenome,window,tadRange,plotInsulation,plotTadDomains,randomBins)
  File "HiCPlotter.py", line 145, in read_sparseHiCdata
    if plotInsulation or plotTadDomains and not wholeGenome: nums,tricks=insulation(matrix,ins_window,rel_window)
  File "HiCPlotter.py", line 367, in insulation
    if isnan(matrix[j][j-2*counter]): diag +=0 # pad with zeros for nan
TypeError: only length-1 arrays can be converted to Python scalars

Best,
Yu

**Comment by kcakdemir** [comment]
I guess it's about the input file. Normally the default HiC-Pro output should work fine. 
You can try to rerun without "-pi 1" to test whether it's only about the insulation function or the input files.

**Comment by yuzhang0327** [comment]
I have removed the "-pi 1" , the same error still came out, FYI, I attached part of my input file here.
[test_40000_iced.matrix.txt](https://github.com/kcakdemir/HiCPlotter/files/1009789/test_40000_iced.matrix.txt)

**Comment by kcakdemir** [comment]
your files seems okay. can you also remove "-ptd 1 -pptd 1 -w 8 -tr 10" parameters, so we can see it if the error would change or not.

**Comment by kcakdemir** [comment]
can you please run just the following, with the current version of HiCPlotter:

python HiCPlotter.py -f matrix -tri 1 -bed bedFile -n mES -chr chr2 -r 100000 -o default2 -s 600 -e 900

you should not receive any error regarding ins_score

**Comment by kcakdemir** [comment]
I am closing this issue, please re-open it, if need be
