### ISSUE TITLE
Normalization by number of reads

### ISSUE THREAD

**Issue by Aurasg** [kcakdemir/HiCPlotter#17]
Hello, my name is Aura Stephenson and I am a student from the UNAM in Mexico from Mayra Furlan's lab. Our lab is working with HiC technique and we are using HiCPlotter to visualize the interaction matrices. We analyzed the HiC data with HiCPro but we have a question about the normalization of the data using HiCPlotter. We want to compare the HiC maps between samples and I saw that it can be done with the tools of HiCPlotter. My question is if the iced normalization that is made by the HiCPro is sufficient for comparing the matrices or if we have to normalize with the number of reads for a real comparison.  

Thank you very much. 
Aura Stephenson

Lab. 202 sur Instituto de Fisiología Celular, UNAM

**Comment by kcakdemir** [comment]
Dear Aura,
Thanks for using HiCPlotter! The comparison function within HiCPlotter does not normalize the row differences between matrices and serves as a visualization function. Therefore, I would suggest you to check the row counts between differences as iced matrices have normalized row counts within a matrix but not necessarily among matrices. 
I do not have much experience but, you might like to check available tools to normalize Hi-C matrices such as HiCdiff (https://github.com/dozmorovlab/HiCdiff).
Please let me know if I could be of any help. Kadir
