### ISSUE TITLE
colorbar

### ISSUE THREAD

**Issue by RuiqinZheng** [kcakdemir/HiCPlotter#20]
Hi,
Thanks for your software that I can make heatmap very fast.
I hava a question about the colobar,when I draw the whole genome's heatmap,there's no colorbar under the heatmap,how can i draw a colorbar under the whole genome's heatmap?
Best wishes
Ruiqin Zheng

**Comment by kcakdemir** [comment]
Please check the new version. It should print colorbar for the whole genome plotting.
