### ISSUE TITLE
mpl_toolkits.axes_grid1 Module Issue

### ISSUE THREAD

**Issue by awezmm** [kcakdemir/HiCPlotter#28]
Hi, I am trying to run the command: 
`python HiCPlotter.py -f data/HiC/Human/HUVEC-chr10_25kb.RAWobserved_KRnormalizedMatrix.txt data/HiC/Human/IMR90-chr10_25kb.RAWobserved_KRnormalizedMatrix.txt -chr chr10 -n HUVEC IMR90 -o comparison -s 4850 -e 5400 -mm 8 -r 25000 -c 1 -t data/HiC/Human/HUVEC_18_core_K27ac_dense2.bed data/HiC/Human/IMR90_18_core_K27ac_dense2.bed -tl States States -spi 1 -hist data/HiC/Human/wgEncodeUwRepliSeqHuvecWaveSignalRep1.bedGraph data/HiC/Human/wgEncodeUwRepliSeqImr90WaveSignalRep1.bedGraph -hl RepliSeq RepliSeq -fhist 1 1`
from the manual.

However, I get the error: 
Traceback (most recent call last):
  File "HiCPlotter.py", line 14, in <module>
    from mpl_toolkits.axes_grid1 import make_axes_locatable
ImportError: No module named mpl_toolkits.axes_grid1

I have already:
`sudo pip install scipy --upgrade`
`sudo pip install numpy --upgrade`
`sudo pip install matplotlib --upgrade`

Im using Python 2.7.15

**Comment by kcakdemir** [comment]
Hi,
I think the issue is with your matplotlib installation. Check this post, perhaps you can use one of the recommendations

https://stackoverflow.com/questions/18596410/importerror-no-module-named-mpl-toolkits-with-maptlotlib-1-3-0-and-py2exe

**Comment by awezmm** [comment]
Thank you for response. It was actually an issue with the specific version of matplotlib being download. 
Since HiCPlotter uses python 2.7.*, i just used pip2 install for everything to make sure I install the correct version that works with Python 2.
