### ISSUE TITLE
How to view .hic files

### ISSUE THREAD

**Issue by awezmm** [kcakdemir/HiCPlotter#29]
What is the best way to view a .hic file which is already storing all the contact matrices? Basically, I have two . files and I want to compare them using the HiC Plotter compare function. It seems that a matrix file is needed for HiC plotter, but I was wondering if there was a way to get a full matrix file from the .hic file
Thanks

**Comment by kcakdemir** [comment]
Hi,
It's a good point. I started implementing to import .hic files in HiCPlotter but it's still not ready.
You can use straw function from Aiden lab to extract a particular regions interactions from a .hic file (https://github.com/aidenlab/straw/wiki/Python).
I hope this helps.
