### ISSUE TITLE
Hi-C Pro mode problem

### ISSUE THREAD

**Issue by ustcahwry** [kcakdemir/HiCPlotter#3]
Hi,
Thank you very much for this plotting tool! When I was using Hi-CPro format file to plot, it could not generate the TAD plot and triangular plot.
Thanks

**Comment by kcakdemir** [comment]
Hi, do you mind sharing how (with which parameters) did you run the HiCPlotter?

**Comment by ustcahwry** [comment]
I run with python  HiCPlotter.py -f hic24hr.matrix -chr chr5 -o hic24hr -r 20000 -bed hic24hr_ord.bed -n chr5 -tri 1 -ptd 1

**Comment by kcakdemir** [comment]
You need to use -ptr for triangular plot, -ptd is a deprecated parameter and I did not implemented it for HiC-Pro format. I would suggest you to use -pptd for plotting published TADs or you can check the manual for other TAD callers. I will close this issue if you dont have any futher comments/questions?

**Comment by ustcahwry** [comment]
Thank you very much

**Comment by kcakdemir** [comment]
No problem! Thanks for contacting!

**Comment by kcakdemir** [comment]
Hi, 

If you would like to run the same command, updated HiCPlotter should work fine now (although I still suggest you to use other TAD caller).
