### ISSUE TITLE
How to draw normalized HiC map with blue_red color?

### ISSUE THREAD

**Issue by skytguuu** [kcakdemir/HiCPlotter#30]
Hi,

Recently, I tried to use HiCPlotter to draw normalized HiC matrix. Because my normalized matrix includes negative value (such as -4.606-08), so I was wondering how to draw this matrix as a HiC map with blue-red color?

Thanks!
Best,
Garen

**Comment by kcakdemir** [comment]
Hi Garen,

You would need to modify the script at a couple of points:

Line 729, you need to change cmap=cmap to cmap='bwr'
Line 758, you should comment it out #img.set_clim([0,cmatrix])

When you run the script also use -nl 1

Let me know if you will have any problems.
Kadir

**Comment by kcakdemir** [comment]
Hi Garen, sure - let me know whats your question is

**Comment by skytguuu** [comment]
Thanks for your reply. The parameter "-ext" could produce pdf file. But I met a error that:
#########
Traceback (most recent call last):
  File "/home/dell/softwares/tools/HiC/HiCPlotter-master/HiCPlotter.py", line 2171, in <module>
    HiCplotter(**args)
  File "/home/dell/softwares/tools/HiC/HiCPlotter-master/HiCPlotter.py", line 683, in HiCplotter
    matrix,nums,tricks,clength,fourClike=read_sparseHiCdata(files[exp],chromosome,bedFile,start,end,wholeGenome,smoothNoise,window,tadRange,plotInsulation,plotTadDomains,randomBins,anchor)
  File "/home/dell/softwares/tools/HiC/HiCPlotter-master/HiCPlotter.py", line 136, in read_sparseHiCdata
    if int(tags[0]) <= end and int(tags[0])>=start :
ValueError: invalid literal for int() with base 10: '123775 123775 181.71612425'
#########
I don't know why it failed. Any suggestion?

Thanks,
Best,
Garen

**Comment by skytguuu** [comment]
Thanks for your reply. The parameter "-ext" could produce pdf file. Is any parameter could change the font size and type? 

Thanks,
Best,
Garen

**Comment by kcakdemir** [comment]
Hi Garen,
You can search the code and change the font size of the part you are interested with. Currently, there is not a way to change font size or type. Best - kadir
