### ISSUE TITLE
How to plot interaction heatmap as Triangle shape and add TAD information I alread have  as annotation ？

### ISSUE THREAD

**Issue by qianXX** [kcakdemir/HiCPlotter#35]
Can I use HiCPlotter to plot TAD and interaction heatmap as Triangle shape?

Just list the figure in this link:
http://promoter.bx.psu.edu/hi-c/fig1.2.png

Thanks!

**Comment by kcakdemir** [comment]
Hi,
You can use "-ptr 1" to plot rotated half matrix and "-trh BIN_NUMBER" to adjust the range of the triangle plot.
