### ISSUE TITLE
TAD boundary files

### ISSUE THREAD

**Issue by Mr-Inamn** [kcakdemir/HiCPlotter#37]
Hi, 

Can HiCPlotter give the TAD boundary or TAD domain coordinates into an additional file? Many thanks.

**Comment by kcakdemir** [comment]
Hi,
I would recommend you to use previously tested TAD callers. You can find more information from the following studies about how each caller performs:

https://academic.oup.com/nar/article/45/6/2994/3059658
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1596-9
https://www.nature.com/articles/nmeth.4325

If you specifically want the regions that HiCPlotter calls then you can start printing the called regions by adding a print before line 529 and see if those regions are useful for you:

	if triple: pBorders=map(lambda x:x+mstart, pBorders)
	if cooler: pBorders=map(lambda x:x+mstart, pBorders)
        print pBorders
	return scores, pBorders
