### ISSUE TITLE
How can I set the length-width ratio of  output PDF file

### ISSUE THREAD

**Issue by liencau** [kcakdemir/HiCPlotter#39]

**Comment by kcakdemir** [comment]
You can modify the below part by changing (numOfcols*5+1, numOfrows+numOfrows/2+0.5) ratio and determine which one works better for you:

if len(files) == 1:
	fig=plt.figure(figsize=(numOfcols*5+1, numOfrows+numOfrows/2+0.5), facecolor='w', edgecolor='w')
	fig.set_size_inches(numOfcols*5+1, numOfrows+numOfrows/2+0.5)
else:
	fig=plt.figure(figsize=(numOfcols*5+2.5, numOfrows+numOfrows/2+0.5), facecolor='w', edgecolor='w')
	fig.set_size_inches(numOfcols*5+2.5, numOfrows+numOfrows/2+0.5)
