### ISSUE TITLE
bedGraph format

### ISSUE THREAD

**Issue by will-NYGC** [kcakdemir/HiCPlotter#4]
I'm trying to add bedgraph histogram plots to my HiC matrix plots. I'm trying to use the example data you included in the data directory:
data/HiC/Human/wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph.gz

I'm testing on 1Mb matrix data but i'm getting this error:
BedGraph(wgEncodeBroadHistoneGm12878CtcfStdSig.chr15.bedGraph.gz) has some missing values

do i need to do any formatting on this? I assumed it would downscale the resolution to fit my window size.

**Comment by kcakdemir** [comment]
Yes it should downscale your Hi-C data resolution. Are you trying to plot chromosome 15 or any other chromosome? Example file has values only for the chromosome 15 and HiCPlotter raises an error for the bedGraph file if chromosome names are not matching or if it cant find any values in the bedGraph file for the give genomic interval.

**Comment by will-NYGC** [comment]
i see. yea i have a whole genome file and only want chr15. so all i need to do is filter my file to remove the other chr? cool, thank you!

**Comment by kcakdemir** [comment]
Bedgraph file can have multiple chromosomes in it. if Hi-C input file is in triple-sparse-file than it should be work fine. wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph has values only for chromosome 15 and therefore can only be used with -chr chr15 plottings.
If you can paste your example run here, I can try to help...

**Comment by will-NYGC** [comment]
Thanks. I am using triple-sparse.

python2.7 /nethome/wliao/tools/HiCPlotter/HiCPlotter.py -f Sample_NPC_553L_1000000_iced.matrix 
Sample_NPC_553L/raw/1000000/Sample_NPC_553L_1000000.matrix -n NPC_553L_1000000_iced NPC_553L_1000000 -chr chr15 -s 2500 -e 2550 -o hic_results/matrix/Sample_NPC_553L/Sample_NPC_553L_1000000 -tri 1 -bed Sample_NPC_553L_1000000_abs.bed -pcd 1 -pcdf Sample_NPC_553L_1000000_iced.TADs.bg Sample_NPC_553L_1000000.TADs.bg -r 1000000 -ptr 1 -hist wgEncodeBroadHistoneGm12878CtcfStdSig.chr15.bedGraph.gz,wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph.gz wgEncodeBroadHistoneGm12878CtcfStdSig.chr15.bedGraph.gz,wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph.gz -hl GM12878-CTCF,K562-CTCF GM12878-CTCF,K562-CTCF -fhist 1,1 1,1 -hc 143D52,9ACD32 143D52,9ACD32

Here's the exact error:
BedGraph(/nethome/wliao/tools/HiCPlotter/data/HiC/Human/wgEncodeBroadHistoneGm12878CtcfStdSig.chr15.bedGraph.gz) has some missing values

**Comment by kcakdemir** [comment]
can you try to run with -s 0 -e 50?

**Comment by will-NYGC** [comment]
still get same error.

On Feb 22, 2016, at 2:59 PM, Kadir Akdemir <notifications@github.com<mailto:notifications@github.com>> wrote:


can you try to run with -s 0 -e 50?

—
Reply to this email directly or view it on GitHub<https://github.com/kcakdemir/HiCPlotter/issues/4#issuecomment-187357949>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by kcakdemir** [comment]
One more thing: gunzip the bedGraph files please :)

**Comment by will-NYGC** [comment]
all bedgraph are gzip’d but still no luck. just to clarify, everything works well without the hist plots.

(really appreciate the help)



On Feb 22, 2016, at 3:31 PM, Kadir Akdemir <notifications@github.com<mailto:notifications@github.com>> wrote:


One more thing: gunzip the bedGraph files please :)

—
Reply to this email directly or view it on GitHub<https://github.com/kcakdemir/HiCPlotter/issues/4#issuecomment-187370885>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by kcakdemir** [comment]
you mean uncompressed right?

**Comment by will-NYGC** [comment]
yes uncompressed didn’t work.

On Feb 22, 2016, at 3:37 PM, Kadir Akdemir <notifications@github.com<mailto:notifications@github.com>> wrote:


you mean uncompressed right?

—
Reply to this email directly or view it on GitHub<https://github.com/kcakdemir/HiCPlotter/issues/4#issuecomment-187372659>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by kcakdemir** [comment]
Can you check what might be different in your run compared to this?

python HiCPlotter.py -f TripleColumn/GSE35156_GSM892306_hESC_HindIII_HiC_replicate.nodup.hic.summary.txt.1000000.matrix TripleColumn/GSE35156_GSM892306_hESC_HindIII_HiC_replicate.nodup.hic.summary.txt.1000000.matrix -tri 1 -bed TripleColumn/GSE35156_GSM892306_hESC_HindIII_HiC_replicate.nodup.hic.summary.txt.1000000_ord.bed -r 1000000 -o test2 -chr chr15 -s 0 -e 50 -n X Y -hist HiCPlotterR/data/HiC/Human/wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph HiCPlotterR/data/HiC/Human/wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph -hl CTCF -hc 143D52

![testx-chr15 ofbins 0-50 1000k](https://cloud.githubusercontent.com/assets/10368164/13232161/912beea2-d973-11e5-8dbf-6145107a6371.jpeg)

**Comment by kcakdemir** [comment]
Sorry check this one: 

python HiCPlotter.py -f TripleColumn/GSE35156_GSM892306_hESC_HindIII_HiC_replicate.nodup.hic.summary.txt.1000000.matrix -tri 1 -bed TripleColumn/GSE35156_GSM892306_hESC_HindIII_HiC_replicate.nodup.hic.summary.txt.1000000_ord.bed -r 1000000 -o test -chr chr15 -s 0 -e 50 -n X -hist HiCPlotterR/data/HiC/Human/wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph -hl CTCF -hc 143D52

**Comment by will-NYGC** [comment]
where can I find the triple column example files? i don’t see them in github. i’m thinking could be issue with my triple column file although it is the direct output of HiCPro.

On Feb 22, 2016, at 3:51 PM, Kadir Akdemir <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry check this one:

python HiCPlotter.py -f TripleColumn/GSE35156_GSM892306_hESC_HindIII_HiC_replicate.nodup.hic.summary.txt.1000000.matrix -tri 1 -bed TripleColumn/GSE35156_GSM892306_hESC_HindIII_HiC_replicate.nodup.hic.summary.txt.1000000_ord.bed -r 1000000 -o test -chr chr15 -s 0 -e 50 -n X -hist HiCPlotterR/data/HiC/Human/wgEncodeBroadHistoneK562CtcfStdSig.chr15.bedGraph -hl CTCF -hc 143D52

—
Reply to this email directly or view it on GitHub<https://github.com/kcakdemir/HiCPlotter/issues/4#issuecomment-187377559>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by kcakdemir** [comment]
I get those files from @nservant, and not sure whether files are publicly available. Let me ask him and then I can direct you to their website. It might have something to do with the bed file for the bin's location?

**Comment by nservant** [comment]
Hi guys,
Examples of HiC-Pro output files are available here : https://zerkalo.curie.fr/partage/HiC-Pro/
Did you test both raw and iced matrices ? Raw matrices should be better to first avoid any issue with the normalization ...

**Comment by will-NYGC** [comment]
just to confirm, i reordered the chrom.sizes file to match the order used in the example data and it all works well now. thanks nicolas, thanks kadir for your help.


On Feb 23, 2016, at 2:27 PM, Nicolas Servant <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi guys,
Examples of HiC-Pro output files are available here : https://zerkalo.curie.fr/partage/HiC-Pro/
Did you test both raw and iced matrices ? Raw matrices should be better to first avoid any issue with the normalization ...

—
Reply to this email directly or view it on GitHub<https://github.com/kcakdemir/HiCPlotter/issues/4#issuecomment-187853500>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by kcakdemir** [comment]
Great to hear it works well now! I will look into the sorting issue and write a note on the readme site about it. I'm closing this issue.
