### ISSUE TITLE
How to set the same  coordinate system for two ChIP data?

### ISSUE THREAD

**Issue by liufuyan2016** [kcakdemir/HiCPlotter#41]
Dear professor,
I draw  two ChIP data  under the Hi-C heatmap use HiCPlotter, but there is two different in Y axis. One is labled 0,2,4，the other is 0,8,16. In other word, there is different coordinate scales in Y axis.I want to make the same coordinate scales in Y axis for comparing two different ChIP data.
Could you help me ? Thank you!

**Comment by kcakdemir** [comment]
Hi there,
You can use -hm 16,16 (or any other numbers) to plot the ChIP data with the same y-axis max values.
Let me know if you have any issues. Best - Kadir
