### ISSUE TITLE
Trouble loading matrix

### ISSUE THREAD

**Issue by kellermac** [kcakdemir/HiCPlotter#6]
Hi I have Hi-C data I have downloaded from GEO. The files are called GEOxxx-IC-heatmaps.txt. They are tab delimited. The first row/column contains the chromosome and the "bin" that is to be correlated. 2L:0K    2L:20K    2L:40K   2L:60K   2L:80K ect.

When I try to plot using the command :  python HiCPlotter.py -wg 1 -f GSE69013_BG3_merged_IC-heatmap-20K.txt -n bg3 -chr chrY -o bg3

I get the message: 
Traceback (most recent call last):
  File "HiCPlotter.py", line 1485, in <module>
    HiCplotter(**args)
  File "HiCPlotter.py", line 520, in HiCplotter
    matrix,nums,tricks=read_HiCdata(files[exp],fileHeader,fileFooter,cleanNANs,smoothNoise,window,tadRange,plotInsulation,plotTadDomains,randomBins)
  File "HiCPlotter.py", line 53, in read_HiCdata
    matrix = np.genfromtxt(filename,skip_header=header,filling_values='0',skip_footer=footer) 
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1769, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #2 (got 6024 columns instead of 6023)
    Line #3 (got 6024 columns instead of 6023)
    Line #4 (got 6024 columns instead of 6023)
    Line #5 (got 6024 columns instead of 6023)
......
.....
.....
    Line #6024 (got 6024 columns ins
tead of 6023)

I tried to fix this using the -fh 1 option. This seems to work (computes for a minute) then gives me this message: 6023 6024
unbalanced matrix(GSE69013_BG3_merged_IC-heatmap-20K.txt)! input should be a square matrix

Any guidance or advise would be vastly appreciated. -Keller

**Comment by kcakdemir** [comment]
Hi,

Your input matrix can have header columns but not rows, you can generate such matrix by using:

cuf -f 2- GSE69013_BG3_merged_IC-heatmap-20K.txt.gz > BG3.20K.matrix

Then you can run HiCPlotter with -fh parameter (also -r for resolution). Here is an example run:

python HiCPlotter.py -wg 1 -f BG3.20K.matrix -n bg3 -chr chrY -o bg3 -fh 1 -r 20000

**Comment by kcakdemir** [comment]
Sorry, it should be 

cut -f 2- GSE69013_BG3_merged_IC-heatmap-20K.txt.gz > BG3.20K.matrix

**Comment by kellermac** [comment]
Thank you for the solution. However I find that the original matrix file GSE69013_BG3_merged_IC-heatmap-20K.txt.gz should be unzipped before cutting.

**Comment by kcakdemir** [comment]
Sorry, I forgot to mention that. Next time, you can use:

gunzip -c GSE69013_BG3_merged_IC-heatmap-20K.txt.gz | cut -f 2- > BG3.20K.matrix
