### ISSUE TITLE
HiC-Pro adaption | sparse triplet format

### ISSUE THREAD

**Issue by Krannich479** [kcakdemir/HiCPlotter#8]
Hej, 
I was glad to read you adapted the format of the HiC-Pro pipeline. Nevertheless I can't get things done if I try to pass the sparse triplet file. Can you have a look if I miss a thing/ do it wrong?
I tried:
`python HiCPlotter.py -f /my/path/rawdata_1000000_iced.matrix -n hicpro_mm9_iced_wg -chr chrY -o /my/path/contactmaps/hicpro_mm9_iced_wg`
Where "rawdata_1000000_iced.matrix" is my sparse triplets file. I get the error message:
> unbalanced matrix(/my/path/rawdata_1000000_iced.matrix)! input should be a square matrix

but this is exactly what I like to avoid, converting it to a square matrix before.
Any suggestions?
Thanks, 
TK

**Comment by Krannich479** [comment]
just found out about the -tri flag, going to give it a try

**Comment by Krannich479** [comment]
hej, 
with -tri 1 and a BED file it works fine at first now. But I still struggle with whole genome plotting:
`python HiCPlotter.py -f /path/my.triplets -n my.name -r 1000000 -chr chrY -fh 0 -tri 1 -bed /path/my.triplets.bed -o /path/my.outfile.prefix`
According to the README, "-wg 1" doesn't work with triplets files, but instead you are ought to put in "-chr chrY" to plot from Chr1 to ChrY (more or less whole genome). It compiles and plots but the output is just a minor sub-part of ChrY. The outfile receives a postfix to "my.outfile.prefix-chrY.ofBins(0-15).1000K.png", telling me it plotted bins 0-15 of ChrY. So I guess it comes down to the question 'WHY does it plot that sub-part of ChrY instead of the whole genome'?

Input triplets and BED file are ok. (all chromosomes included.)

Thanks!

**Comment by kcakdemir** [comment]
Hi,

I need to update the README page but you can use -wg 1 with triple sparse files. 
You just need to add -wg 1 to your current command and you will get the whole genome plotting. If you want to plot interactions from 1 to 15 then instead of chrY, you should use chr15.

Thanks, Kadir
