### ISSUE TITLE
-ptr

### ISSUE THREAD

**Issue by dalessandra** [kcakdemir/HiCPlotter#9]
Dear Kadir,

Thank you for developing HiCPlotter, it's an incredible tool!

I wanted to ask you if it is possible to change the scale of the rotated half matrix. The triangles are cut in half in my case.

Thank you very much!!

Best,
Ale

PS: -ptr default is 0 in the new version, not 1 :)

**Comment by kcakdemir** [comment]
Hi Ale,

Thanks for using HiCPlotter!

Do you mind letting me know about your resolution and size of the genomic window you are visualizing? I'm trying to improve the visualization of the rotated matrix, perhaps I can add a new parameter for changing the height.
Yes, I had changed -ptr default to 0, but I guess I forgot to change it somewhere in the docs :)

Take care,
Kadir

**Comment by dalessandra** [comment]
Hi Kadir,

Thank you for the fast reply! 

My resolution is 40kb and the genomic window is chr17 32Mb-33Mb. If the genomic window is bigger the visualization is much better!

Thank you very much!!
Best,
Ale

**Comment by kcakdemir** [comment]
Thanks Ale! Let me work on it and I will update you on this issue... Kadir

**Comment by dalessandra** [comment]
Thanks Kadir!!!! Ale

**Comment by kcakdemir** [comment]
Hi Ale,

Please check the updated version of HiCPlotter. There is now a new parameter (-trh) to adjust the height of triangular plots. Default value is (end bin-start bin)/5. So you can run with different values to decide which one works best for. Examples: 

with -trh:

python HiCPlotter.py -f hES-nij.chr7.2 IMR90-nij.chr7.2 -n hES IMR90 -chr chr7 -ptr 1 -hist H1.H3K27me3.chr7.bedGraph,H1.Pol2.chr7.bedGraph IMR90.H3K27me3.chr7.bedGraph,IMR90.Pol2.chr7.bedGraph -hl H3K27me3,PolII H3K27me3,PolII -s 650 -e 700 -o trh -r 40000 -mm 7 -trh 20 -spi 1

![trh-chr7 ofbins 650-700 40k](https://cloud.githubusercontent.com/assets/10368164/18277270/7e6044cc-7413-11e6-8f67-2a75a1c47142.jpeg)

Default run:

python HiCPlotter.py -f hES-nij.chr7.2 IMR90-nij.chr7.2 -n hES IMR90 -chr chr7 -ptr 1 -hist H1.H3K27me3.chr7.bedGraph,H1.Pol2.chr7.bedGraph IMR90.H3K27me3.chr7.bedGraph,IMR90.Pol2.chr7.bedGraph -hl H3K27me3,PolII a,b -s 650 -e 700 -o default -r 40000 -mm 7

![default-chr7 ofbins 650-700 40k](https://cloud.githubusercontent.com/assets/10368164/18277271/7e63dcfe-7413-11e6-804a-ad5339e34506.jpeg)

**Comment by kcakdemir** [comment]
Hi Ale, I'm going to close this issue, but please re-open it if need be.
